### ISSUE TITLE
Feature request: ability to manually set the repo url

### ISSUE THREAD

**Issue by sandervanburken** [Graylog2/graylog2-cookbook#69] opened 2016-09-05 14:11 UTC
The default recipe sets up the repo but doesn't allow to set a different repo URL. It would improve the cookbook if that is possible because then you do need to workaround this if a server does not have internet access.

The workaround is to not include the `graylog2::default` recipe and manually check for the correct java version and set up the repo.

**Comment by mariussturm** [comment] 2016-09-05 15:33
The problem is that you have to change the repo URL for each supported platform manually when it's stored in an attribute. Thats why we split the server recipe from the default in the first place. Any suggestions how to implement this are welcome.

**Comment by mariussturm** [comment] 2016-09-07 18:35
This is possible with current master and will be in 2.1.3 https://github.com/Graylog2/graylog2-cookbook/blob/master/attributes/default.rb#L10

**Closed by mariussturm** 2016-09-07 18:35 UTC

**Comment by sandervanburken** [comment] 2016-09-09 09:49
Thank you for implementing this feature!
